### ISSUE TITLE
Identifying the workflows

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-docs#15]
Identifying the workflows needed for better execution of the project and assigning them to people

**Comment by Sddilora** [comment]
- Open issues for implementing the CI/CD processes to:
 - [x] [Validate branch names according to naming conventions](https://github.com/octoposprime/op-be-docs/issues/17)
   - [x] Assign
- [x] [Apply topic, priority, and company labels to all issues](https://github.com/octoposprime/op-infra/issues/50)
  - [x] Assign
- [x] [Verify that only authorized team leads can change project status](https://github.com/octoposprime/op-be-docs/issues/19)
  - [x] Assign
- [x] [Enforce short titles for issues and pull requests (ideally within 40-50 characters)](https://github.com/octoposprime/op-be-docs/issues/20)
  - [x] Assign
- [x] [Apply appropriate labels to pull requests](https://github.com/octoposprime/op-be-docs/issues/21)
  - [x] Assign
- [x] [Ensure that issues with status other than "new" or "backlog" have estimation and iteration](https://github.com/octoposprime/op-infra/issues/49)
  - [x] Assign
- [x] [Automatically set issue status to "in review" when mentioned in a pull request](https://github.com/octoposprime/op-be-docs/issues/23)
  - [x] Assign
- [x] [Establish a method to track the start of an issue and set its status to "ready" (e.g., creating a branch from the issue)](https://github.com/octoposprime/op-be-docs/issues/24)
  - [x] Assign

**Comment by Sddilora** [comment]
@Feyzanrs, could you please assign the issues to the appropriate members?
After completing the assignment, please update the issue status to "ready" and tick the assign fields in the list above.

**Comment by Feyzanrs** [comment]
All issues have been successfully assigned to the appropriate team members and their statuses have been updated to 'ready'.
